version: '3.8'
services:
  # api:
  #   image: 'golang:1.22'
  #   ports:
  #     - '8000:8000'
  proxy:
    image: 'golang:1.22'
    ports:
      - '8080:8080'
    volumes:
      - '${PWD}/proxy:/app'
    restart: always
    working_dir: '/app'
    command: sh -c 'go run ./cmd/proxy/main.go'